expressions:
  NEW_KEYWORD_Angry: SignAngry.exp3.json
  NEW_KEYWORD_Eyes_Cry: EyesCry.exp3.json
  NEW_KEYWORD_Heart_Eyes: EyesLove.exp3.json
  NEW_KEYWORD_Shock: Shock.exp3.json
vts_settings:
  host: 127.0.0.1
  port: 8001
  token_file: vts_token.txt
