# This file maps languages to their corresponding sherpa-onnx models.
# It uses the transducer-based models that are already present and correctly formatted.

en:
  model_name: "sherpa-onnx-streaming-zipformer-en-20M-2023-02-17"
  url: "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-en-20M-2023-02-17.tar.bz2"
  params:
    encoder: "encoder-epoch-99-avg-1.int8.onnx"
    decoder: "decoder-epoch-99-avg-1.int8.onnx"
    joiner: "joiner-epoch-99-avg-1.int8.onnx"
    tokens: "tokens.txt"

zh_Hant:
  model_name: "sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20"
  url: "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20.tar.bz2"
  params:
    encoder: "encoder-epoch-99-avg-1.int8.onnx"
    decoder: "decoder-epoch-99-avg-1.int8.onnx"
    joiner: "joiner-epoch-99-avg-1.int8.onnx"
    tokens: "tokens.txt"
