en:
  url: "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-en-20M-2023-02-17.tar.bz2"
  tokens: "tokens.txt"
  encoder: "encoder-epoch-99-avg-1.int8.onnx"
  decoder: "decoder-epoch-99-avg-1.int8.onnx"
  joiner: "joiner-epoch-99-avg-1.int8.onnx"
zh:
  url: "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20.tar.bz2"
  tokens: "tokens.txt"
  encoder: "encoder-epoch-99-avg-1.int8.onnx"
  decoder: "decoder-epoch-99-avg-1.int8.onnx"
  joiner: "joiner-epoch-99-avg-1.int8.onnx"
ja:
  url: "https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-ja-2023-05-28.tar.bz2"
  tokens: "tokens.txt"
  encoder: "encoder-epoch-99-avg-1.onnx"
  decoder: "decoder-epoch-99-avg-1.onnx"
  joiner: "joiner-epoch-99-avg-1.onnx"