en:
  window_title: "VTS Voice Controller"
  vts_status: "VTS Status:"
  asr_status: "ASR Status:"
  app_status: "App Status:"
  vts_status_disconnected: "Disconnected"
  asr_status_idle: "Idle"
  app_status_stopped: "Stopped"
  recognition_mode: "Recognition Mode:"
  language: "Language:"
  provider: "Provider:"
  start_button: "Start Application"
  stop_button: "Stop Application"
  log_placeholder: "Live Transcription Output..."
  header_expression: "Expression Name"
  header_keywords: "Keywords"
  header_cooldown: "Cooldown (s)"
zh:
  window_title: "VTS语音控制器"
  vts_status: "VTS状态:"
  asr_status: "ASR状态:"
  app_status: "应用状态:"
  vts_status_disconnected: "已断开"
  asr_status_idle: "空闲"
  app_status_stopped: "已停止"
  recognition_mode: "识别模式:"
  language: "语言:"
  provider: "提供者:"
  start_button: "启动应用"
  stop_button: "停止应用"
  log_placeholder: "实时语音识别输出..."
  header_expression: "表情名称"
  header_keywords: "关键词"
  header_cooldown: "冷却(秒)"
ja:
  window_title: "VTS音声コントローラー"
  vts_status: "VTSステータス:"
  asr_status: "ASRステータス:"
  app_status: "アプリステータス:"
  vts_status_disconnected: "切断されました"
  asr_status_idle: "アイドル"
  app_status_stopped: "停止"
  recognition_mode: "認識モード:"
  language: "言語:"
  provider: "プロバイダー:"
  start_button: "アプリケーションを開始"
  stop_button: "アプリケーションを停止"
  log_placeholder: "ライブ文字起こし出力..."
  header_expression: "表情名"
  header_keywords: "キーワード"
  header_cooldown: "クールダウン(秒)"