en:
  window_title: "VTS Voice Controller"
  status_label: "Status:"
  status_disconnected: "Disconnected"
  status_connected: "Connected"
  start_button: "Start Application"
  stop_button: "Stop Application"
  mode_label: "Recognition Mode:"
  language_label: "Language:"
  transcription_placeholder: "Live Transcription Output..."
  header_expression: "Expression Name"
  header_keywords: "Keywords"
  header_cooldown: "Cooldown (s)"